title: PyamilySeq
author:
  name: NickJD
  email: nicholas@dimonaco.co.uk

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >-
  PyamilySeq

url: https://nickjd.github.io/PyamilySeq/


theme: just-the-docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template


